# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SlrVulnerabilityMapper
                                 A QGIS plugin
 Assess and visualize sea‑level‑rise & flood exposure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-17
        copyright            : (C) 2025 by Christian Xavier Corral Burau
        email                : christianxcorral@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Christian Xavier Corral Burau'
__date__ = '2025-08-17'
__copyright__ = '(C) 2025 by Christian Xavier Corral Burau'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SlrVulnerabilityMapper class from file SlrVulnerabilityMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .slr_vulnerability_mapper import SlrVulnerabilityMapperPlugin
    return SlrVulnerabilityMapperPlugin(iface)
